# Example parameter file, see parameters_launch.py

# Format is namespace_name/node_name
my_camera/gscam_publisher:
  ros__parameters:
    # gscam_config: 'videotestsrc ! video/x-raw, format=BGRx ! videoconvert'
    gscam_config: 'nvarguscamerasrc sensor-id=0 !
      video/x-raw(memory:NVMM), width=(int)1280, height=(int)720, framerate=(fraction)30/1 !
      nvvidconv flip-method=2 !
      video/x-raw, width=(int)640, height=(int)480, format=(string)BGRx !
      videoconvert !
      video/x-raw, format=(string)BGR'
    preroll: False
    use_gst_timestamps: False
    frame_id: 'camera_frame_id'
